// ============================================================
// COSMIC FRONTIER - Game Configuration
// All game data: locations, resources, technologies, buildings
// ============================================================

const CONFIG = {

  // ---- RESOURCES ----
  RESOURCES: {
    iron:          { name: 'Iron',          icon: '🔩', color: '#cd7f32', desc: 'Basic structural metal' },
    silicon:       { name: 'Silicon',       icon: '💎', color: '#a0b4c8', desc: 'Electronics and solar panels' },
    carbon:        { name: 'Carbon',        icon: '◆',  color: '#555', desc: 'Versatile construction material' },
    water:         { name: 'Water',         icon: '💧', color: '#4169e1', desc: 'Fuel & life support' },
    helium3:       { name: 'Helium-3',      icon: '⚡', color: '#ffd700', desc: 'Clean fusion fuel' },
    titanium:      { name: 'Titanium',      icon: '🔷', color: '#b0c4de', desc: 'Super-strong alloy metal' },
    platinum:      { name: 'Platinum',      icon: '✦',  color: '#e5e4e2', desc: 'Rare catalyst' },
    regolith:      { name: 'Regolith',      icon: '🪨', color: '#a8917a', desc: 'Lunar surface material' },
    ice:           { name: 'Ice',           icon: '❄️',  color: '#a8d8ea', desc: 'Water ice deposits' },
    hydrogen:      { name: 'Hydrogen',      icon: '○',  color: '#e0f0ff', desc: 'Rocket propellant' },
    methane:       { name: 'Methane',       icon: '🌫️', color: '#88aa66', desc: 'Hydrocarbon fuel' },
    crystals:      { name: 'Crystals',      icon: '💠', color: '#9b59b6', desc: 'Resonant cosmic crystals' },
    nitrogen:      { name: 'Nitrogen',      icon: '🌀', color: '#aaccff', desc: 'Atmospheric gas' },
    diamonds:      { name: 'Diamonds',      icon: '💍', color: '#b9f2ff', desc: 'Extreme pressure gem' },
    neutronium:    { name: 'Neutronium',    icon: '⬛', color: '#222', desc: 'Ultra-dense neutron matter' },
    exoticMatter:  { name: 'Exotic Matter', icon: '✧',  color: '#ff44ff', desc: 'Negative mass particles' },
    darkMatter:    { name: 'Dark Matter',   icon: '◉',  color: '#330055', desc: 'Invisible binding force' },
    alienCrystals: { name: 'Alien Crystals',icon: '⬡',  color: '#00ff88', desc: 'Ancient alien tech artifact' },
    quantumDust:   { name: 'Quantum Dust',  icon: '✨', color: '#ff88ff', desc: 'Entangled particle clouds' },
    antimatter:    { name: 'Antimatter',    icon: '⊛',  color: '#ff2200', desc: 'Annihilation fuel' },
    voidEssence:   { name: 'Void Essence',  icon: '◈',  color: '#110022', desc: 'Essence of nothingness' },
    flightData:    { name: 'Flight Data',   icon: '📊', color: '#44aaff', desc: 'Telemetry from unmanned test missions' },
  },

  // ---- LOCATIONS ----
  LOCATIONS: {
    earth: {
      name: 'Earth', icon: '🌍', color: '#4a90d9', ringColor: null,
      distance: 0, distanceUnit: 'AU',
      description: 'Our home planet. Rich in iron and silicon.',
      resources: ['iron', 'silicon', 'carbon', 'water'],
      baseYield: { iron: 1.0, silicon: 0.6, carbon: 0.4, water: 0.3 },
      unlocked: true,
      flavorText: 'The cradle of humanity. Our journey begins here.',
    },
    moon: {
      name: 'The Moon', icon: '🌕', color: '#aaaaaa', ringColor: null,
      distance: 0.0026, distanceUnit: 'AU',
      description: 'Earth\'s natural satellite. Contains helium-3 from solar winds.',
      resources: ['iron', 'silicon', 'regolith', 'helium3'],
      baseYield: { iron: 0.8, silicon: 0.5, regolith: 1.2, helium3: 0.3 },
      unlocked: false,
      requires: { tech: 'chemical_rockets' },
      flavorText: 'Humanity\'s first step beyond Earth.',
    },
    mars: {
      name: 'Mars', icon: '🔴', color: '#c1440e', ringColor: null,
      distance: 1.52, distanceUnit: 'AU',
      description: 'The Red Planet. Vast mineral reserves beneath the rusty surface.',
      resources: ['iron', 'silicon', 'carbon', 'ice'],
      baseYield: { iron: 1.5, silicon: 0.8, carbon: 0.7, ice: 0.5 },
      unlocked: false,
      requires: { tech: 'ion_propulsion' },
      flavorText: 'The Red Planet beckons. Terraform or mine?',
    },
    asteroidBelt: {
      name: 'Asteroid Belt', icon: '🪨', color: '#8b7355', ringColor: null,
      distance: 2.7, distanceUnit: 'AU',
      description: 'Millions of rocky bodies rich in rare metals.',
      resources: ['iron', 'titanium', 'platinum', 'carbon'],
      baseYield: { iron: 2.5, titanium: 1.0, platinum: 0.4, carbon: 0.8 },
      unlocked: false,
      requires: { tech: 'deep_space_nav' },
      flavorText: 'Untold riches float freely here.',
    },
    jupiter: {
      name: 'Jupiter', icon: '🟠', color: '#c88b3a', ringColor: null,
      distance: 5.2, distanceUnit: 'AU',
      description: 'The gas giant. Harvest hydrogen and helium-3 from the atmosphere.',
      resources: ['hydrogen', 'helium3', 'ice'],
      baseYield: { hydrogen: 3.0, helium3: 1.2, ice: 0.8 },
      unlocked: false,
      requires: { tech: 'nuclear_thermal' },
      flavorText: 'The Great Red Spot swirls with ancient storms.',
    },
    europa: {
      name: 'Europa', icon: '⚪', color: '#d4e8f0', ringColor: null,
      distance: 5.2, distanceUnit: 'AU',
      description: 'Jupiter\'s icy moon. A subsurface ocean hides beneath the ice.',
      resources: ['ice', 'silicon', 'carbon', 'water'],
      baseYield: { ice: 2.0, silicon: 0.6, carbon: 0.5, water: 1.5 },
      unlocked: false,
      requires: { base: 'jupiter' },
      flavorText: 'Life may lurk beneath the frozen shell...',
    },
    saturn: {
      name: 'Saturn', icon: '🪐', color: '#e8d5a3', ringColor: '#f0e68c',
      distance: 9.58, distanceUnit: 'AU',
      description: 'Ringed gas giant. The rings are rich in ice and minerals.',
      resources: ['hydrogen', 'helium3', 'ice', 'crystals'],
      baseYield: { hydrogen: 2.5, helium3: 1.5, ice: 2.0, crystals: 0.3 },
      unlocked: false,
      requires: { tech: 'antimatter_init' },
      flavorText: 'The most beautiful planet in the solar system.',
    },
    titan: {
      name: 'Titan', icon: '🟡', color: '#f4a460', ringColor: null,
      distance: 9.58, distanceUnit: 'AU',
      description: 'Saturn\'s largest moon. Thick atmosphere of nitrogen and methane.',
      resources: ['nitrogen', 'methane', 'crystals', 'ice'],
      baseYield: { nitrogen: 2.0, methane: 1.8, crystals: 0.8, ice: 1.0 },
      unlocked: false,
      requires: { base: 'saturn' },
      secret: true,
      secretThreshold: 500, // crystals mined to trigger secret
      flavorText: 'Strange orange skies hide ancient secrets...',
    },
    uranus: {
      name: 'Uranus', icon: '🔵', color: '#7de8e8', ringColor: '#5cc0c0',
      distance: 19.2, distanceUnit: 'AU',
      description: 'Ice giant tilted on its side. Rich in exotic ices and diamonds.',
      resources: ['ice', 'diamonds', 'methane', 'exoticMatter'],
      baseYield: { ice: 3.0, diamonds: 0.5, methane: 2.0, exoticMatter: 0.1 },
      unlocked: false,
      requires: { tech: 'quantum_propulsion' },
      flavorText: 'Pressure here forges diamonds from carbon.',
    },
    neptune: {
      name: 'Neptune', icon: '🟣', color: '#3f54ba', ringColor: '#2a3888',
      distance: 30.1, distanceUnit: 'AU',
      description: 'The most distant true planet. Fierce winds carry exotic matter.',
      resources: ['ice', 'helium3', 'diamonds', 'neutronium'],
      baseYield: { ice: 2.5, helium3: 2.0, diamonds: 0.8, neutronium: 0.2 },
      unlocked: false,
      requires: { tech: 'quantum_propulsion' },
      flavorText: 'Supersonic winds of 2100 km/h scour the surface.',
    },
    kuiperBelt: {
      name: 'Kuiper Belt', icon: '🌌', color: '#6a8bad', ringColor: null,
      distance: 40, distanceUnit: 'AU',
      description: 'The outer solar system belt. Gateway to interstellar space.',
      resources: ['ice', 'platinum', 'exoticMatter', 'quantumDust'],
      baseYield: { ice: 2.0, platinum: 1.0, exoticMatter: 0.5, quantumDust: 0.2 },
      unlocked: false,
      requires: { tech: 'warp_coils' },
      secret: true,
      secretThreshold: 200,
      flavorText: 'At the edge of the solar system, reality grows thin.',
    },
    proxima: {
      name: 'Proxima Centauri', icon: '⭐', color: '#ff6b6b', ringColor: null,
      distance: 4.24, distanceUnit: 'LY',
      description: 'The nearest star to our Sun. An alien system awaits.',
      resources: ['alienCrystals', 'exoticMatter', 'quantumDust', 'darkMatter'],
      baseYield: { alienCrystals: 1.5, exoticMatter: 1.0, quantumDust: 0.8, darkMatter: 0.3 },
      unlocked: false,
      requires: { tech: 'warp_drive' },
      flavorText: 'Another sun. Another hope. The stars are within reach.',
    },
    proximaB: {
      name: 'Proxima b', icon: '🌑', color: '#882200', ringColor: null,
      distance: 4.24, distanceUnit: 'LY',
      description: 'A rocky world in Proxima\'s habitable zone.',
      resources: ['alienCrystals', 'iron', 'darkMatter', 'voidEssence'],
      baseYield: { alienCrystals: 2.0, iron: 3.0, darkMatter: 0.5, voidEssence: 0.1 },
      unlocked: false,
      requires: { base: 'proxima' },
      secret: true,
      secretThreshold: 100,
      flavorText: 'Ancient ruins cover the surface. Someone was here before us.',
    },
    alphaCentauri: {
      name: 'Alpha Centauri', icon: '🌟', color: '#ffdd44', ringColor: null,
      distance: 4.37, distanceUnit: 'LY',
      description: 'A binary star system. Two suns, immense energy available.',
      resources: ['darkMatter', 'antimatter', 'quantumDust', 'voidEssence'],
      baseYield: { darkMatter: 1.0, antimatter: 0.5, quantumDust: 1.5, voidEssence: 0.3 },
      unlocked: false,
      requires: { tech: 'hyperdrive' },
      flavorText: 'Two suns bathe this system in golden light.',
    },
    voidNexus: {
      name: 'The Void Nexus', icon: '🌀', color: '#220033', ringColor: '#440066',
      distance: 1000, distanceUnit: 'LY',
      description: 'A tear in spacetime itself. The ultimate frontier.',
      resources: ['voidEssence', 'antimatter', 'darkMatter', 'alienCrystals'],
      baseYield: { voidEssence: 2.0, antimatter: 1.5, darkMatter: 2.0, alienCrystals: 1.0 },
      unlocked: false,
      requires: { tech: 'void_navigation' },
      flavorText: 'Beyond this point, the laws of physics are... suggestions.',
    },
  },

  // ---- TECHNOLOGIES ----
  TECHS: {
    // === TIER 0: Earth Foundation ===
    basic_mining: {
      name: 'Advanced Mining Drills',
      tier: 0, icon: '⛏',
      desc: 'Improved drill heads increase mining speed by 75%.',
      cost: { iron: 30, silicon: 10 },
      researchTime: 8,
      effect: { miningMultiplier: 1.75 },
      unlocks: [],
      requires: [],
    },
    solar_panels: {
      name: 'Solar Panels',
      tier: 0, icon: '☀️',
      desc: 'Harness solar energy to power auto-miners.',
      cost: { iron: 40, silicon: 30 },
      researchTime: 12,
      effect: { enableAutoMine: true },
      unlocks: ['auto_miner'],
      requires: ['basic_mining'],
    },
    chemical_rockets: {
      name: 'Chemical Rockets',
      tier: 0, icon: '🚀',
      desc: 'Basic rocket propulsion. Enables travel to the Moon.',
      cost: { iron: 80, silicon: 40, carbon: 20 },
      researchTime: 30,
      effect: {},
      unlocks: ['rocket_basic'],
      requires: ['solar_panels'],
      unlockLocation: 'moon',
    },

    // === TIER 1: Inner Solar System ===
    fuel_refinement: {
      name: 'Fuel Refinement',
      tier: 1, icon: '⚗️',
      desc: 'Refine helium-3 for better fuel efficiency. Mining yields +50%.',
      cost: { iron: 120, silicon: 80, helium3: 20 },
      researchTime: 45,
      effect: { miningMultiplier: 1.5 },
      unlocks: [],
      requires: ['chemical_rockets'],
    },
    ion_propulsion: {
      name: 'Ion Propulsion',
      tier: 1, icon: '⚡',
      desc: 'Electrically accelerated ions for efficient deep space travel. Unlocks Mars.',
      cost: { iron: 200, silicon: 150, helium3: 50 },
      researchTime: 60,
      effect: {},
      unlocks: ['rocket_ion'],
      requires: ['fuel_refinement'],
      unlockLocation: 'mars',
    },
    base_construction: {
      name: 'Base Construction',
      tier: 1, icon: '🏗',
      desc: 'Build permanent outposts on other worlds.',
      cost: { iron: 150, silicon: 100, carbon: 80 },
      researchTime: 50,
      effect: { enableBases: true },
      unlocks: ['base_module'],
      requires: ['chemical_rockets'],
    },
    deep_space_nav: {
      name: 'Deep Space Navigation',
      tier: 1, icon: '🗺',
      desc: 'Advanced navigation for the outer solar system. Unlocks Asteroid Belt.',
      cost: { iron: 300, silicon: 200, carbon: 100, helium3: 80 },
      researchTime: 90,
      effect: {},
      unlocks: ['rocket_heavy'],
      requires: ['ion_propulsion', 'base_construction'],
      unlockLocation: 'asteroidBelt',
    },

    // === TIER 2: Outer Solar System ===
    nuclear_thermal: {
      name: 'Nuclear Thermal Drive',
      tier: 2, icon: '☢️',
      desc: 'Nuclear-heated propellant for high thrust. Unlocks Jupiter.',
      cost: { iron: 500, titanium: 200, helium3: 150, silicon: 300 },
      researchTime: 120,
      effect: { miningMultiplier: 2.0 },
      unlocks: ['rocket_nuclear'],
      requires: ['deep_space_nav'],
      unlockLocation: 'jupiter',
    },
    antimatter_init: {
      name: 'Antimatter Research',
      tier: 2, icon: '⊛',
      desc: 'Initial studies into antimatter production. Unlocks Saturn.',
      cost: { titanium: 400, platinum: 100, helium3: 300, silicon: 500 },
      researchTime: 180,
      effect: {},
      unlocks: ['rocket_antimatter_basic'],
      requires: ['nuclear_thermal'],
      unlockLocation: 'saturn',
    },
    cryo_tech: {
      name: 'Cryogenic Technology',
      tier: 2, icon: '❄️',
      desc: 'Store resources in cryogenic tanks. Storage capacity ×5.',
      cost: { titanium: 300, ice: 200, silicon: 400 },
      researchTime: 150,
      effect: { storageMultiplier: 5 },
      unlocks: [],
      requires: ['nuclear_thermal'],
    },

    // === TIER 3: Secret of Titan (Unlocked by Titan discovery) ===
    quantum_propulsion: {
      name: 'Quantum Propulsion',
      tier: 3, icon: '🌀',
      desc: '[ CLASSIFIED - TITAN DISCOVERY ] Exploit quantum tunneling for FTL-adjacent travel. Unlocks outer planets.',
      cost: { crystals: 500, helium3: 1000, titanium: 800, exoticMatter: 50 },
      researchTime: 300,
      effect: { miningMultiplier: 3.0 },
      unlocks: ['rocket_quantum'],
      requires: [], // unlocked by event
      locked: true,
      unlockLocation: 'uranus',
      unlockLocationAlt: 'neptune',
    },
    warp_coils: {
      name: 'Warp Field Coils',
      tier: 3, icon: '〰️',
      desc: '[ CLASSIFIED ] Coils that distort spacetime around a vessel. Unlocks Kuiper Belt.',
      cost: { crystals: 800, exoticMatter: 200, diamonds: 100, quantumDust: 50 },
      researchTime: 360,
      effect: {},
      unlocks: ['rocket_warp'],
      requires: ['quantum_propulsion'],
      locked: true,
      unlockLocation: 'kuiperBelt',
    },
    warp_drive: {
      name: 'Warp Drive',
      tier: 3, icon: '🚀',
      desc: '[ CLASSIFIED ] Full warp drive. Faster-than-light travel. Unlocks nearby stars.',
      cost: { exoticMatter: 500, quantumDust: 300, crystals: 1000, darkMatter: 100 },
      researchTime: 600,
      effect: { miningMultiplier: 4.0 },
      unlocks: ['rocket_warp_full'],
      requires: ['warp_coils'],
      locked: true,
      unlockLocation: 'proxima',
    },

    // === TIER 4: Interstellar (Unlocked by Kuiper Belt secret) ===
    dark_matter_engine: {
      name: 'Dark Matter Engine',
      tier: 4, icon: '◉',
      desc: '[ BEYOND HUMAN SCIENCE ] Harness dark matter for virtually unlimited propulsion.',
      cost: { darkMatter: 500, antimatter: 200, voidEssence: 50, alienCrystals: 300 },
      researchTime: 900,
      effect: { miningMultiplier: 5.0 },
      unlocks: [],
      requires: ['warp_drive'],
      locked: true,
    },
    hyperdrive: {
      name: 'Hyperdrive',
      tier: 4, icon: '✦',
      desc: '[ BEYOND HUMAN SCIENCE ] Instantaneous jumps across light-years.',
      cost: { darkMatter: 800, antimatter: 400, alienCrystals: 600, quantumDust: 500 },
      researchTime: 1200,
      effect: {},
      unlocks: ['rocket_hyper'],
      requires: ['dark_matter_engine'],
      locked: true,
      unlockLocation: 'alphaCentauri',
    },

    // === TIER 5: Void (Unlocked by Proxima b secret) ===
    void_navigation: {
      name: 'Void Navigation',
      tier: 5, icon: '◈',
      desc: '[ ANCIENT ALIEN KNOWLEDGE ] Navigate the fabric of space itself. The final frontier.',
      cost: { voidEssence: 1000, darkMatter: 1000, antimatter: 800, alienCrystals: 1000 },
      researchTime: 1800,
      effect: { miningMultiplier: 10.0 },
      unlocks: ['rocket_void'],
      requires: ['hyperdrive'],
      locked: true,
      unlockLocation: 'voidNexus',
    },
  },

  // ---- ROCKETS ----
  ROCKETS: {
    rocket_basic: {
      name: 'Chemical Rocket',
      icon: '🚀', tier: 1,
      crewed: false,
      desc: 'Unmanned probe rocket. Too primitive for a human crew. Sends a probe to collect samples and data.',
      cost: { iron: 150, silicon: 80, carbon: 40 },
      buildTime: 60,
      range: ['moon'],
      requires: 'chemical_rockets',
    },
    rocket_ion: {
      name: 'Ion Drive Ship',
      icon: '⚡', tier: 2,
      desc: 'First crewed spacecraft. Efficient ion drive for inner solar system travel.',
      cost: { iron: 300, silicon: 200, helium3: 80, titanium: 50 },
      buildTime: 120,
      range: ['moon', 'mars'],
      requires: 'ion_propulsion',
    },
    rocket_heavy: {
      name: 'Heavy Lifter',
      icon: '🛸', tier: 2,
      desc: 'Massive cargo rocket for the asteroid belt and beyond.',
      cost: { iron: 600, titanium: 200, helium3: 150, silicon: 300 },
      buildTime: 180,
      range: ['moon', 'mars', 'asteroidBelt'],
      requires: 'deep_space_nav',
    },
    rocket_nuclear: {
      name: 'Nuclear Drive',
      icon: '☢️', tier: 3,
      desc: 'Nuclear thermal drive for the outer solar system.',
      cost: { titanium: 500, helium3: 300, platinum: 100, silicon: 400 },
      buildTime: 240,
      range: ['moon','mars','asteroidBelt','jupiter','europa'],
      requires: 'nuclear_thermal',
    },
    rocket_antimatter_basic: {
      name: 'Antimatter Probe',
      icon: '⊛', tier: 3,
      desc: 'Antimatter-powered for the entire solar system.',
      cost: { titanium: 800, helium3: 500, platinum: 300, crystals: 100 },
      buildTime: 300,
      range: ['moon','mars','asteroidBelt','jupiter','europa','saturn','titan'],
      requires: 'antimatter_init',
    },
    rocket_quantum: {
      name: 'Quantum Jumper',
      icon: '🌀', tier: 4,
      desc: 'Uses quantum tunneling to skip vast distances.',
      cost: { crystals: 800, exoticMatter: 200, titanium: 1000, quantumDust: 100 },
      buildTime: 600,
      range: ['moon','mars','asteroidBelt','jupiter','europa','saturn','titan','uranus','neptune'],
      requires: 'quantum_propulsion',
    },
    rocket_warp: {
      name: 'Warp Cruiser',
      icon: '〰️', tier: 4,
      desc: 'Warp field generator for near-FTL travel.',
      cost: { exoticMatter: 500, crystals: 1000, diamonds: 200, quantumDust: 300 },
      buildTime: 900,
      range: ['moon','mars','asteroidBelt','jupiter','europa','saturn','titan','uranus','neptune','kuiperBelt'],
      requires: 'warp_coils',
    },
    rocket_warp_full: {
      name: 'Warp Drive Flagship',
      icon: '🌟', tier: 5,
      desc: 'Full warp capability. The stars are within reach.',
      cost: { exoticMatter: 1500, darkMatter: 300, quantumDust: 800, alienCrystals: 200 },
      buildTime: 1800,
      range: ['moon','mars','asteroidBelt','jupiter','europa','saturn','titan','uranus','neptune','kuiperBelt','proxima','proximaB'],
      requires: 'warp_drive',
    },
    rocket_hyper: {
      name: 'Hyperdrive Vessel',
      icon: '✦', tier: 5,
      desc: 'Instant jumps across light-years.',
      cost: { darkMatter: 1000, antimatter: 500, alienCrystals: 800, voidEssence: 100 },
      buildTime: 3600,
      range: ['moon','mars','asteroidBelt','jupiter','europa','saturn','titan','uranus','neptune','kuiperBelt','proxima','proximaB','alphaCentauri'],
      requires: 'hyperdrive',
    },
    rocket_void: {
      name: 'Void Ship',
      icon: '◈', tier: 6,
      desc: 'Navigates through the Void itself. True cosmic exploration.',
      cost: { voidEssence: 2000, antimatter: 1000, darkMatter: 2000, alienCrystals: 1500 },
      buildTime: 7200,
      range: null, // Everywhere
      requires: 'void_navigation',
    },
  },

  // ---- BUILDINGS ----
  BUILDINGS: {
    auto_miner: {
      name: 'Auto-Miner',
      icon: '🤖',
      desc: 'Automatically mines resources over time.',
      costBase: { iron: 60, silicon: 30 },
      costScale: 1.5, // Each additional costs 1.5x more
      productionMultiplier: 0.2, // 20% of click yield per second
      requires: 'solar_panels',
      maxPerLocation: 10,
    },
    base_module: {
      name: 'Base Module',
      icon: '🏗',
      desc: 'Establishes a permanent outpost. Enables auto-mining at this location.',
      costBase: { iron: 200, silicon: 150, carbon: 100 },
      costScale: 2.0,
      requires: 'base_construction',
      maxPerLocation: 1,
      isBase: true,
    },
    refinery: {
      name: 'Refinery',
      icon: '⚗️',
      desc: 'Refines raw materials into purer forms. +100% yield on all resources here.',
      costBase: { iron: 300, titanium: 100, silicon: 200 },
      costScale: 1.8,
      productionMultiplier: 2.0,
      requires: 'fuel_refinement',
      maxPerLocation: 3,
      requiresBase: true,
    },
    research_lab: {
      name: 'Research Lab',
      icon: '🔬',
      desc: 'Remote research laboratory. Speeds up all research by 10% per lab.',
      costBase: { silicon: 400, iron: 200, carbon: 200 },
      costScale: 2.5,
      researchSpeedBonus: 0.1,
      requires: 'base_construction',
      maxPerLocation: 5,
      requiresBase: true,
    },
    deep_drill: {
      name: 'Deep Drill',
      icon: '🔩',
      desc: 'Drills deep beneath the surface for bonus rare resources.',
      costBase: { titanium: 200, iron: 400, helium3: 100 },
      costScale: 2.0,
      rareResourceBonus: 0.5,
      requires: 'deep_space_nav',
      maxPerLocation: 3,
      requiresBase: true,
    },
    signal_array: {
      name: 'Signal Array',
      icon: '📡',
      desc: 'Scans for anomalies and secrets. Required for secret discoveries.',
      costBase: { silicon: 500, titanium: 300, helium3: 200 },
      costScale: 2.0,
      requires: 'deep_space_nav',
      maxPerLocation: 1,
      requiresBase: true,
      enablesSecrets: true,
    },
    fusion_reactor: {
      name: 'Fusion Reactor',
      icon: '⚡',
      desc: 'Helium-3 fusion reactor. Powers everything and doubles output.',
      costBase: { helium3: 300, titanium: 500, platinum: 100 },
      costScale: 3.0,
      productionMultiplier: 3.0,
      requires: 'nuclear_thermal',
      maxPerLocation: 2,
      requiresBase: true,
    },
    quantum_transmitter: {
      name: 'Quantum Transmitter',
      icon: '🌀',
      desc: 'Transmits resources instantly via quantum entanglement.',
      costBase: { crystals: 300, exoticMatter: 100, quantumDust: 50 },
      costScale: 2.0,
      enablesAutoTransfer: true,
      requires: 'quantum_propulsion',
      maxPerLocation: 1,
      requiresBase: true,
    },
  },

  // ---- SECRETS / EVENTS ----
  SECRETS: {
    titan_signal: {
      location: 'titan',
      trigger: 'crystals_mined',
      threshold: 500,
      requiresBuilding: 'signal_array',
      title: '📡 ANOMALOUS SIGNAL DETECTED',
      messages: [
        'Your signal array on Titan is picking up a structured electromagnetic pattern...',
        'The pattern is non-random. It repeats with mathematical precision.',
        'Cross-referencing with known languages and mathematical systems...',
        '⚠️ MATCH FOUND: The signal encodes advanced physics equations.',
        '🔓 DECODING COMPLETE: QUANTUM ENTANGLEMENT PROPULSION PROTOCOL',
        'The equations describe a method to exploit quantum tunneling for propulsion.',
        'This technology did not originate from Earth. Someone left this for us.',
        '🌌 NEW TECHNOLOGIES UNLOCKED: Quantum Propulsion, Warp Coils, Warp Drive',
      ],
      unlockTechs: ['quantum_propulsion', 'warp_coils', 'warp_drive'],
      reward: { crystals: 1000, exoticMatter: 50 },
    },
    kuiper_anomaly: {
      location: 'kuiperBelt',
      trigger: 'quantumDust_mined',
      threshold: 200,
      requiresBuilding: 'signal_array',
      title: '🌌 SPACETIME ANOMALY DETECTED',
      messages: [
        'Your sensors at the Kuiper Belt detect an impossible reading...',
        'Space itself seems... thinner here. The boundary between dimensions is weak.',
        'Quantum dust concentrations form geometric patterns spanning thousands of kilometers.',
        '🔭 ANALYSIS: This is not a natural formation.',
        'The patterns encode dark matter manipulation techniques.',
        'A second alien civilization? Or the same one, leaving more breadcrumbs?',
        '🔓 DECODED: DARK MATTER ENGINE and HYPERDRIVE schematics received.',
        '🌟 NEW TECHNOLOGIES UNLOCKED: Dark Matter Engine, Hyperdrive',
      ],
      unlockTechs: ['dark_matter_engine', 'hyperdrive'],
      reward: { darkMatter: 200, alienCrystals: 100 },
    },
    proxima_ruins: {
      location: 'proximaB',
      trigger: 'alienCrystals_mined',
      threshold: 100,
      requiresBuilding: 'signal_array',
      title: '👾 ALIEN RUINS DISCOVERED',
      messages: [
        'Surface scans of Proxima b reveal massive geometric structures...',
        'They are ancient. Carbon dating suggests 2 billion years old.',
        'Inside the largest structure: a library, encoded in pure mathematics.',
        '📖 The builders called themselves the Architects of the Void.',
        'They traveled between galaxies using... the Void itself.',
        'A substrate beneath normal spacetime, accessible through pure mathematics.',
        '🔓 VOID NAVIGATION PROTOCOLS TRANSFERRED TO YOUR SYSTEMS.',
        '◈ THE FINAL FRONTIER AWAITS. NEW TECHNOLOGY UNLOCKED: Void Navigation',
      ],
      unlockTechs: ['void_navigation'],
      reward: { voidEssence: 200, antimatter: 100 },
    },
  },

  // ---- ACHIEVEMENTS ----
  ACHIEVEMENTS: [
    { id: 'first_mine', name: 'First Strike', desc: 'Mine your first resource.', icon: '⛏', trigger: 'totalMined', value: 1 },
    { id: 'moon_landing', name: 'One Small Step', desc: 'Reach the Moon.', icon: '🌕', trigger: 'location', value: 'moon' },
    { id: 'mars_arrival', name: 'Red Pioneer', desc: 'Set foot on Mars.', icon: '🔴', trigger: 'location', value: 'mars' },
    { id: 'first_base', name: 'Home Away From Home', desc: 'Build your first off-world base.', icon: '🏗', trigger: 'basesBuilt', value: 1 },
    { id: 'titan_secret', name: 'The Signal', desc: 'Discover the secret of Titan.', icon: '📡', trigger: 'secret', value: 'titan_signal' },
    { id: 'warp_tech', name: 'Warp Factor One', desc: 'Unlock warp drive technology.', icon: '🌀', trigger: 'tech', value: 'warp_drive' },
    { id: 'proxima', name: 'Interstellar', desc: 'Reach Proxima Centauri.', icon: '⭐', trigger: 'location', value: 'proxima' },
    { id: 'alien_ruins', name: 'Ancient Architects', desc: 'Discover the alien ruins on Proxima b.', icon: '👾', trigger: 'secret', value: 'proxima_ruins' },
    { id: 'void_nexus', name: 'Into the Void', desc: 'Reach the Void Nexus.', icon: '🌀', trigger: 'location', value: 'voidNexus' },
    { id: 'resource_1k', name: 'Thousand Fold', desc: 'Mine 1,000 of any resource.', icon: '💰', trigger: 'singleResource', value: 1000 },
    { id: 'resource_100k', name: 'Industrial Might', desc: 'Mine 100,000 total resources.', icon: '🏭', trigger: 'totalMined', value: 100000 },
    { id: 'all_solar', name: 'Solar Sovereign', desc: 'Establish bases on all solar system bodies.', icon: '🌞', trigger: 'basesCount', value: 8 },
  ],

  // ---- GAME SETTINGS ----
  SETTINGS: {
    saveInterval: 10000,      // Auto-save every 10 seconds
    tickRate: 100,            // Game tick every 100ms (10 per second)
    baseStorage: 500,         // Default resource storage
    clickParticles: 8,        // Number of particles on click
    notificationDuration: 4000, // How long notifications show (ms)
    researchLabSpeedBonus: 0.1, // 10% faster per lab
  },
};
